PYTORCH WORK

CUDA AND PYTORCH INITIALIZATION

In [2]:
import torch
print(torch.cuda.is_available())  # Devrait retourner True
print(torch.cuda.get_device_name(0))  # Nom de ton GPU

True
NVIDIA GeForce RTX 3050 Ti Laptop GPU


In [3]:
# Vérifie que CUDA est disponible
if torch.cuda.is_available():
    device = torch.device('cuda')  # GPU
else:
    device = torch.device('cpu')  # Si le GPU n'est pas disponible

# Exemple avec un tensor
x = torch.rand(3, 3)
x = x.to(device)  # Déplace le tensor vers le GPU ou CPU

print(x)

tensor([[0.6636, 0.2245, 0.8721],
        [0.9764, 0.0721, 0.7391],
        [0.9034, 0.7213, 0.4648]], device='cuda:0')


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## TENSORS
### creating tensors

In [5]:
scalar = torch.tensor(12)
print(scalar)
print(scalar.ndim)


tensor(12)
0


In [6]:
scalar.item()

12

In [7]:
vector = torch.tensor([12, 12])
print(vector)
print(vector.ndim)
vector.shape



tensor([12, 12])
1


torch.Size([2])

In [8]:
matrix = torch.tensor([[4,3], 
                       [2,1]])
print(matrix)
print(matrix.ndim)
matrix.shape



tensor([[4, 3],
        [2, 1]])
2


torch.Size([2, 2])

## RANDOM TENSORS

In [9]:
random_tensor = torch.rand(3,5)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)


## ZEROS AND ONES
zeros = torch.zeros(2,3)
print(zeros)
print(zeros.ndim)
print(zeros.shape)

ones = torch.ones(2,3)
print(ones)
print(ones.ndim)
print(ones.shape)

## TENSOR OPERATIONS




tensor([[0.3980, 0.7071, 0.7591, 0.2979, 0.3084],
        [0.0462, 0.6833, 0.2097, 0.9366, 0.4147],
        [0.2431, 0.9437, 0.6881, 0.6032, 0.3431]])
2
torch.Size([3, 5])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
2
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
2
torch.Size([2, 3])


In [10]:
random_image_size_tensor = torch.rand(3, 224, 224)
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)



tensor([[[0.7787, 0.5484, 0.3318,  ..., 0.3915, 0.8521, 0.5942],
         [0.9205, 0.7718, 0.7938,  ..., 0.1863, 0.8433, 0.9460],
         [0.7553, 0.7955, 0.5494,  ..., 0.9207, 0.0977, 0.6067],
         ...,
         [0.4971, 0.9685, 0.6206,  ..., 0.6237, 0.8038, 0.6627],
         [0.3025, 0.4981, 0.6368,  ..., 0.8259, 0.2747, 0.3841],
         [0.9102, 0.0333, 0.7872,  ..., 0.3619, 0.1149, 0.6416]],

        [[0.4179, 0.7078, 0.7996,  ..., 0.4122, 0.0250, 0.6900],
         [0.4118, 0.6195, 0.9222,  ..., 0.0312, 0.4778, 0.4755],
         [0.0191, 0.0844, 0.1620,  ..., 0.6187, 0.7088, 0.0678],
         ...,
         [0.4553, 0.5928, 0.2206,  ..., 0.4003, 0.8230, 0.7292],
         [0.1319, 0.2008, 0.0669,  ..., 0.7826, 0.4806, 0.1229],
         [0.2591, 0.8477, 0.5676,  ..., 0.8150, 0.5709, 0.1516]],

        [[0.3983, 0.7761, 0.5617,  ..., 0.9986, 0.1315, 0.2160],
         [0.7286, 0.3689, 0.0082,  ..., 0.6606, 0.3197, 0.4171],
         [0.4819, 0.9736, 0.5245,  ..., 0.5799, 0.7680, 0.

In [11]:
random_image_size_tensor.dtype

torch.float32

## RANGE OF TENSORS

In [12]:
one_to_twenty_a =torch.arange(0,20) #range from 1 to 21
print(one_to_twenty_a)
one_to_twenty_b = torch.arange(start=1, end=21, step=1)
print(one_to_twenty_b)
# do not forget -1 increment 
torch.zeros_like(one_to_twenty_a)




tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
float_tensor = torch.tensor([2.3, 3.2, 4.5], 
                            dtype=torch.float32, # by default is float32
                            device=device, 
                            requires_grad=True)
print(float_tensor)
print(float_tensor.ndim)
print(float_tensor.shape)

float_16_tensor = float_tensor.to(torch.float16)
print(float_16_tensor)





tensor([2.3000, 3.2000, 4.5000], device='cuda:0', requires_grad=True)
1
torch.Size([3])
tensor([2.3008, 3.1992, 4.5000], device='cuda:0', dtype=torch.float16,
       grad_fn=<ToCopyBackward0>)


In [14]:
#convert int32 to float32
int_tensor = torch.tensor([1,2,3], dtype=torch.int32)
print(int_tensor)
print(int_tensor.dtype)

int_to_float = int_tensor.to(torch.float32)
print(int_to_float)
print(int_to_float.dtype)

mixed_tensor = int_tensor*int_to_float
print(mixed_tensor.dtype)
# .shape is an attribute, and .size is a function 



tensor([1, 2, 3], dtype=torch.int32)
torch.int32
tensor([1., 2., 3.])
torch.float32
torch.float32


## Tensors operations
### addition, subtraction, multiplication, division, matrix multiplication

In [15]:
tensor = torch.tensor([1,2,3])
print('from %s' % tensor)
print('tensor + 1: %s' % (tensor + 1))
print('tensor - 1: %s' % (tensor - 1))
print('tensor * 2: %s' % (tensor * 2))
print('tensor / 2: %s' % (tensor / 2))
print('tensor * tensor: %s' % (tensor * tensor))
print('tensor / tensor: %s' % (tensor / tensor))




from tensor([1, 2, 3])
tensor + 1: tensor([2, 3, 4])
tensor - 1: tensor([0, 1, 2])
tensor * 2: tensor([2, 4, 6])
tensor / 2: tensor([0.5000, 1.0000, 1.5000])
tensor * tensor: tensor([1, 4, 9])
tensor / tensor: tensor([1., 1., 1.])


In [25]:
print('from %s' % tensor, 'we apply element wise, dot product and matrix multiplication')
%time print('with * operator: element wise multiplication gives %s' % (tensor*tensor)) # element wise multiplication
%time print('with @ operator: dot product gives %s' % (tensor@tensor)) # dot product
%time print('with the matmul function, matrix multiplication gives %s' % (tensor.matmul(tensor))) # matrix multiplication
print('--> use matmul for speed increase and better performance')





from tensor([1, 2, 3]) we apply element wise, dot product and matrix multiplication
with * operator: element wise multiplication gives tensor([1, 4, 9])
CPU times: user 359 μs, sys: 48 μs, total: 407 μs
Wall time: 296 μs
with @ operator: dot product gives tensor(14)
CPU times: user 129 μs, sys: 0 ns, total: 129 μs
Wall time: 131 μs
with the matmul function, matrix multiplication gives tensor(14)
CPU times: user 87 μs, sys: 0 ns, total: 87 μs
Wall time: 88.7 μs
--> use matmul for speed increase and better performance


## Inner dimmensions must match, resulting matrix has the following shape: (m, n) @ (n, p) = (m, p)

In [33]:
tensor_A = torch.tensor([[1,2],
                        [3,4]])
tensor_B = torch.tensor([[5,6],
                        [7,8]])
%time print(torch.mm(tensor_A, tensor_B))
%time print(tensor_A.matmul(tensor_B))
print('---> it is better to use matmul for speed increase')
print('---> for transpose, use .T at the end of the tensor, Tensor_B.T')

tensor([[19, 22],
        [43, 50]])
CPU times: user 1.17 ms, sys: 25 μs, total: 1.2 ms
Wall time: 997 μs
tensor([[19, 22],
        [43, 50]])
CPU times: user 286 μs, sys: 0 ns, total: 286 μs
Wall time: 186 μs
---> it is better to use matmul for speed increase
---> for transpose, use .T at the end of the tensor, Tensor_B.T


## Finding min, max, mean, sum, argmin, argmax

In [38]:
x = torch.arange(0,100,10)
print(x)
print(x.min())
print(x.max())


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(90)


In [41]:
print('For the mean, use .mean() with float32 or float16, long does not work')
print('torch.mean(x.dtype(float32))')
print('--->', torch.mean(x.type(torch.float32)))



For the mean, use .mean() with float32 or float16, long does not work
torch.mean(x.dtype(float32))
---> tensor(45.)


In [46]:
print('For the sum, use .sum()')
print('---> torch.sum(x)) =', torch.sum(x))
print('---> x.sum() =', x.sum(), 'also works')



For the sum, use .sum()
---> torch.sum(x)) = tensor(450)
---> x.sum() = tensor(450) also works


## argmin and argmax

In [48]:
print(x)
print(x.argmin(), '---> returns the index of the minimum value')
print(x.argmax(), '---> returns the index of the maximum value')





tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) ---> returns the index of the minimum value
tensor(9) ---> returns the index of the maximum value


## Reshaping, stacking, squeezing, unsqueezing
* reshape: reshapes a tensor to a defined shape
* view: returns a view of an input tensor of certain shape but keeps the same memory as original tensor
* squeeze: removes all the 1 dimensions from the shape of a tensor
* unsqueeze: adds an extra dimension to the shape of a tensor



In [61]:
x = torch.arange(1,10)
print(x)
print(x.shape)
print(x.reshape(1,9))
%time print(x.reshape(1,9).shape, '---> use of reshape, see brackets')
print(x.view(1,9))
%time print(x.view(1,9).shape, '---> use of view, see brackets')






tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9]) ---> use of reshape, see brackets
CPU times: user 18 μs, sys: 4 μs, total: 22 μs
Wall time: 24.8 μs
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9]) ---> use of view, see brackets
CPU times: user 36 μs, sys: 8 μs, total: 44 μs
Wall time: 46 μs


In [64]:
z = x.view(1,9)
print(z, z.shape)
z[:, 0] = 5
print(z, z.shape)
print(x)
print('---> stack tensors vertically, use torch.stack')
x_stacked = torch.stack([x,x,x])
print(x_stacked, x_stacked.shape)






tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
---> stack tensors vertically, use torch.stack
tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([3, 9])


## use of squeeze and unsqueeze methods

In [69]:
print(x)
x_reshaped = x.reshape(1,9)
print(x_reshaped)
print(x_reshaped.shape)
print('---> use of squeeze')
print(x_reshaped.squeeze())
print(x_reshaped.squeeze().shape)
print('One dimension is removed, see brackets')


tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])
---> use of squeeze
tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
One dimension is removed, see brackets


In [75]:
print('unsqueeze adds an extra dimension to a target tensor at a specific dim')
print(x_reshaped)
print('---> for dim=0: ',x_reshaped.unsqueeze(dim=0))
print('shape: ',x_reshaped.unsqueeze(dim=0).shape)
print('---> for dim=1: ',x_reshaped.unsqueeze(dim=1))
print('shape: ',x_reshaped.unsqueeze(dim=1).shape)





unsqueeze adds an extra dimension to a target tensor at a specific dim
tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
---> for dim=0:  tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]])
shape:  torch.Size([1, 1, 9])
---> for dim=1:  tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]])
shape:  torch.Size([1, 1, 9])


## Permutations

In [83]:
x_original = torch.rand(size=(224, 224, 3))
print(x_original.shape)
x_permuted = x_original.permute(2,0,1) 
print('shifts axis 0->1, 1->2, 2->0')
print(x_permuted.shape)
print('--> SHARES THE SAME MEMORY AS THE ORIGINAL TENSOR')
x_original[0,0,0] = 100
print('x_original[0,0,0] =', x_original[0,0,0])
print('x_permuted[0,0,0] =', x_permuted[0,0,0], '---> same value without changing it')







torch.Size([224, 224, 3])
shifts axis 0->1, 1->2, 2->0
torch.Size([3, 224, 224])
--> SHARES THE SAME MEMORY AS THE ORIGINAL TENSOR
x_original[0,0,0] = tensor(100.)
x_permuted[0,0,0] = tensor(100.) ---> same value without changing it


## Indexing and Slicing

In [87]:
x = torch.arange(1,10).reshape(1, 3, 3)
print(x, '---> print full tensor')
print(x[0], '---> print first dimension')
print(x[0,0], '---> print first dimension, first element')
print(x[0,0,0], '---> print first dimension, first element, first element')
print(x[0,0,0].item(), '---> returns the value of the tensor')




tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) ---> print full tensor
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) ---> print first dimension
tensor([1, 2, 3]) ---> print first dimension, first element
tensor(1) ---> print first dimension, first element, first element
1 ---> returns the value of the tensor


## Indexing examples

In [90]:
print(x[0][0])
print(x[0,0,:])
print('x[0][0] is the same as x[0,0,:]')

tensor([1, 2, 3])
tensor([1, 2, 3])
x[0][0] is the same as x[0,0,:]


## PyTorch and Numpy

In [100]:
array = np.arange(1.0,10.0)
print(array)
tensor = torch.from_numpy(array)
print('--> when converting from numpy to pytorch, the data type is float64, need to specity to float32')
print(tensor)
array = tensor.numpy()
print(array)



[1. 2. 3. 4. 5. 6. 7. 8. 9.]
--> when converting from numpy to pytorch, the data type is float64, need to specity to float32
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Adding value to tensor and array

In [106]:
array = array + 1
print(array)
print(tensor)
print('--> adding value to array does not change tensor')
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
print('---> converting tensor to numpy, the data type is float32 again')




[ 7.  8.  9. 10. 11. 12. 13. 14. 15.]
tensor([1., 1., 1., 1., 1., 1., 1.])
--> adding value to array does not change tensor
---> converting tensor to numpy, the data type is float32 again


## Reproducibility
### To reduce randomness, set the seed

In [108]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)
print('--> random tensor is not reproducible')




tensor([[0.6631, 0.3612, 0.2596, 0.3011],
        [0.9522, 0.8597, 0.9538, 0.1919],
        [0.7623, 0.1937, 0.6029, 0.4315]])
tensor([[0.1974, 0.1207, 0.4719, 0.3783],
        [0.2016, 0.4390, 0.0036, 0.6808],
        [0.6630, 0.2706, 0.8792, 0.2734]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
--> random tensor is not reproducible


### Random but reproducible tensors

In [110]:
RANDOM_SEED = 22
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A == random_tensor_B)
print('--> random tensor is reproducible, we have to set the seed before the tensor is created')




tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
--> random tensor is reproducible, we have to set the seed before the tensor is created


### Running on GPU 

In [112]:
!nvidia-smi

Fri Jan 17 16:00:36 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8               6W /  35W |    105MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [115]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))





True
1
NVIDIA GeForce RTX 3050 Ti Laptop GPU


In [117]:
print('--> transfer to GPU')
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)




--> transfer to GPU
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


### If tensor on GPU, can't transform it to numpy


In [120]:
tensor_back_on_gpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_gpu, tensor_back_on_gpu.device)

[1 2 3] cpu
