PYTORCH WORK

CUDA AND PYTORCH INITIALIZATION

In [1]:
import torch
print(torch.cuda.is_available())  # Devrait retourner True
print(torch.cuda.get_device_name(0))  # Nom de ton GPU

True
NVIDIA GeForce RTX 3050 Ti Laptop GPU


In [2]:
# Vérifie que CUDA est disponible
if torch.cuda.is_available():
    device = torch.device('cuda')  # GPU
else:
    device = torch.device('cpu')  # Si le GPU n'est pas disponible

# Exemple avec un tensor
x = torch.rand(3, 3)
x = x.to(device)  # Déplace le tensor vers le GPU ou CPU

print(x)

tensor([[0.1082, 0.2257, 0.5090],
        [0.3079, 0.7245, 0.9577],
        [0.9395, 0.8167, 0.1937]], device='cuda:0')


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## TENSORS
### creating tensors

In [6]:
scalar = torch.tensor(12)
print(scalar)
print(scalar.ndim)


tensor(12)
0


In [7]:
scalar.item()

12

In [10]:
vector = torch.tensor([12, 12])
print(vector)
print(vector.ndim)
vector.shape



tensor([12, 12])
1


torch.Size([2])

In [11]:
matrix = torch.tensor([[4,3], 
                       [2,1]])
print(matrix)
print(matrix.ndim)
matrix.shape



tensor([[4, 3],
        [2, 1]])
2


torch.Size([2, 2])

## RANDOM TENSORS

In [12]:
random_tensor = torch.rand(3,5)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)


## ZEROS AND ONES
zeros = torch.zeros(2,3)
print(zeros)
print(zeros.ndim)
print(zeros.shape)

ones = torch.ones(2,3)
print(ones)
print(ones.ndim)
print(ones.shape)

## TENSOR OPERATIONS




tensor([[0.0027, 0.4259, 0.1767, 0.3713, 0.2109],
        [0.1194, 0.7667, 0.9945, 0.1241, 0.9096],
        [0.3226, 0.9836, 0.6194, 0.6321, 0.7991]])
2
torch.Size([3, 5])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
2
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
2
torch.Size([2, 3])


In [13]:
random_image_size_tensor = torch.rand(3, 224, 224)
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)



tensor([[[0.6101, 0.6600, 0.1328,  ..., 0.1902, 0.0609, 0.8602],
         [0.7451, 0.3262, 0.0250,  ..., 0.7940, 0.6111, 0.2945],
         [0.3550, 0.3776, 0.7982,  ..., 0.5674, 0.9564, 0.7708],
         ...,
         [0.1148, 0.6004, 0.0341,  ..., 0.6472, 0.6589, 0.6443],
         [0.2476, 0.6187, 0.1304,  ..., 0.7778, 0.6982, 0.7814],
         [0.9725, 0.1628, 0.1754,  ..., 0.2343, 0.3057, 0.4677]],

        [[0.4649, 0.4380, 0.0116,  ..., 0.9857, 0.7679, 0.7543],
         [0.1780, 0.1803, 0.8444,  ..., 0.9938, 0.4304, 0.2466],
         [0.1861, 0.9425, 0.1161,  ..., 0.1125, 0.8358, 0.1518],
         ...,
         [0.0523, 0.7671, 0.2689,  ..., 0.6467, 0.2494, 0.4699],
         [0.0528, 0.7754, 0.7939,  ..., 0.7166, 0.5513, 0.4353],
         [0.7865, 0.3851, 0.1825,  ..., 0.0556, 0.0776, 0.1481]],

        [[0.5494, 0.7666, 0.4288,  ..., 0.8562, 0.4997, 0.2907],
         [0.7441, 0.8013, 0.4873,  ..., 0.1107, 0.1015, 0.5558],
         [0.1546, 0.3315, 0.0381,  ..., 0.0769, 0.1964, 0.

In [14]:
random_image_size_tensor.dtype

torch.float32

## RANGE OF TENSORS

In [22]:
one_to_twenty_a =torch.arange(0,20) #range from 1 to 21
print(one_to_twenty_a)
one_to_twenty_b = torch.arange(start=1, end=21, step=1)
print(one_to_twenty_b)
# do not forget -1 increment 
torch.zeros_like(one_to_twenty_a)




tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
float_tensor = torch.tensor([2.3, 3.2, 4.5], 
                            dtype=torch.float32, # by default is float32
                            device=device, 
                            requires_grad=True)
print(float_tensor)
print(float_tensor.ndim)
print(float_tensor.shape)

float_16_tensor = float_tensor.to(torch.float16)
print(float_16_tensor)





tensor([2.3000, 3.2000, 4.5000], device='cuda:0', requires_grad=True)
1
torch.Size([3])
tensor([2.3008, 3.1992, 4.5000], device='cuda:0', dtype=torch.float16,
       grad_fn=<ToCopyBackward0>)


In [34]:
#convert int32 to float32
int_tensor = torch.tensor([1,2,3], dtype=torch.int32)
print(int_tensor)
print(int_tensor.dtype)

int_to_float = int_tensor.to(torch.float32)
print(int_to_float)
print(int_to_float.dtype)

mixed_tensor = int_tensor*int_to_float
print(mixed_tensor.dtype)
# .shape is an attribute, and .size is a function 



tensor([1, 2, 3], dtype=torch.int32)
torch.int32
tensor([1., 2., 3.])
torch.float32
torch.float32


## Tensors operations
### addition, subtraction, multiplication, division, matrix multiplication

In [39]:
tensor = torch.tensor([1,2,3])
print('from %s' % tensor)
print('tensor + 1: %s' % (tensor + 1))
print('tensor - 1: %s' % (tensor - 1))
print('tensor * 2: %s' % (tensor * 2))
print('tensor / 2: %s' % (tensor / 2))
print('tensor * tensor: %s' % (tensor * tensor))
print('tensor / tensor: %s' % (tensor / tensor))




from tensor([1, 2, 3])
tensor + 1: tensor([2, 3, 4])
tensor - 1: tensor([0, 1, 2])
tensor * 2: tensor([2, 4, 6])
tensor / 2: tensor([0.5000, 1.0000, 1.5000])
tensor * tensor: tensor([1, 4, 9])
tensor / tensor: tensor([1., 1., 1.])
